[tool.poetry]
name = "prizm"
version = "0.1.0"
description = ""
authors = ["David Nugent <davidn@uniquode.io>"]

[tool.poetry.dependencies]
python = "^3.10"
pygame = "^2.1.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
